[colors]
draw_bold_text_with_bright_colors = true

# [[colors.indexed_colors]]
# color = "#FAB387"
# index = 16

# [[colors.indexed_colors]]
# color = "#F5E0DC"
# index = 17

[cursor]
style = { shape = "Beam" }
vi_mode_style = { shape = "Beam" }

[env]
TERM = "xterm-256color"

[font]
size = 28
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }
normal = { family = "Iosevka Nerd Font", style = "Regular" }
bold = { family = "Iosevka Nerd Font", style = "Bold" }
italic = { family = "Iosevka Nerd Font", style = "Italic" }

[keyboard]
bindings = [
  { action = "Paste", key = "V", mods = "Command" },
  { action = "Copy", key = "C", mods = "Command" },
  { action = "Hide", key = "H", mods = "Command" },
  { action = "Minimize", key = "M", mods = "Command" },
  { action = "ToggleFullscreen", key = "F", mods = "Command|Control" },
  { action = "SpawnNewInstance", key = "N", mods = "Command" },
  { action = "Quit", key = "W", mods = "Command" },
]

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "none"
dynamic_padding = false
opacity = 0.9
startup_mode = "Maximized"
padding = { x = 5, y = 5 }
dimensions = { columns = 60, lines = 40 }

# catppuccin_mocha
[colors.primary]
background = '#1E1E2E' # base
foreground = '#CDD6F4' # text
# Bright and dim foreground colors
dim_foreground = '#CDD6F4'    # text
bright_foreground = '#CDD6F4' # text

# Cursor colors
[colors.cursor]
text = '#1E1E2E'   # base
cursor = '#F5E0DC' # rosewater

[colors.vi_mode_cursor]
text = '#1E1E2E'   # base
cursor = '#B4BEFE' # lavender

# Search colors
[colors.search.matches]
foreground = '#1E1E2E' # base
background = '#A6ADC8' # subtext0

[colors.search.focused_match]
foreground = '#1E1E2E' # base
background = '#A6E3A1' # green

[colors.footer_bar]
foreground = '#1E1E2E' # base
background = '#A6ADC8' # subtext0

# Keyboard regex hints
[colors.hints.start]
foreground = '#1E1E2E' # base
background = '#F9E2AF' # yellow

[colors.hints.end]
foreground = '#1E1E2E' # base
background = '#A6ADC8' # subtext0

# Selection colors
[colors.selection]
text = '#1E1E2E'       # base
background = '#F5E0DC' # rosewater

# Normal colors
[colors.normal]
black = '#45475A'   # surface1
red = '#F38BA8'     # red
green = '#A6E3A1'   # green
yellow = '#F9E2AF'  # yellow
blue = '#89B4FA'    # blue
magenta = '#F5C2E7' # pink
cyan = '#94E2D5'    # teal
white = '#BAC2DE'   # subtext1

# Bright colors
[colors.bright]
black = '#585B70'   # surface2
red = '#F38BA8'     # red
green = '#A6E3A1'   # green
yellow = '#F9E2AF'  # yellow
blue = '#89B4FA'    # blue
magenta = '#F5C2E7' # pink
cyan = '#94E2D5'    # teal
white = '#A6ADC8'   # subtext0

# Dim colors
[colors.dim]
black = '#45475A'   # surface1
red = '#F38BA8'     # red
green = '#A6E3A1'   # green
yellow = '#F9E2AF'  # yellow
blue = '#89B4FA'    # blue
magenta = '#F5C2E7' # pink
cyan = '#94E2D5'    # teal
white = '#BAC2DE'   # subtext1
