import = ["/Users/leo/dotfiles/.config/alacritty/tomorrow_night.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = { shape = "Beam" }
vi_mode_style = { shape = "Beam" }

[env]
TERM = "xterm-256color"

[font]
size = 28
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }
normal = { family = "Iosevka Nerd Font", style = "Regular" }
bold = { family = "Iosevka Nerd Font", style = "Bold" }
italic = { family = "Iosevka Nerd Font", style = "Italic" }

[keyboard]
bindings = [
  { action = "Paste", key = "V", mods = "Command" },
  { action = "Copy", key = "C", mods = "Command" },
  { action = "Hide", key = "H", mods = "Command" },
  { action = "Minimize", key = "M", mods = "Command" },
  { action = "ToggleFullscreen", key = "F", mods = "Command|Control" },
  { action = "SpawnNewInstance", key = "N", mods = "Command" },
  { action = "Quit", key = "W", mods = "Command" },
]

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "none"
dynamic_padding = false
opacity = 0.9
startup_mode = "Maximized"
padding = { x = 5, y = 5 }
dimensions = { columns = 60, lines = 40 }
