# Colors (https://github.com/sane1090x/dotfiles/tree/main)

# Default colors
[colors.primary]
background = '0x1e2326' # base
foreground = '0xd3c6aa' # text

[colors.normal]
black = '0x1e2326'   # surface1
red = '0xe67e80'     # red
green = '0xa7c080'   # green
yellow = '0xdbbc7f'  # yellow
blue = '0x7fbbb3'    # blue
magenta = '0xd699b6' # pink
cyan = '0x83c092'    # teal
white = '0xd3c6aa'   # subtext1

# Bright colors
[colors.bright]
black = '0x475258'   # surface2
red = '0xe67e80'     # red
green = '0xa7c080'   # green
yellow = '0xdbbc7f'  # yellow
blue = '0x7fbbb3'    # blue
magenta = '0xd699b6' # pink
cyan = '0x83c092'    # teal
white = '0xd3c6aa'   # subtext0
